export const BACKGROUND_COLOR = '#2B2B2B'
export const BORDER_COLOR = '#4B4D4D'
export const ITEM_BACKGROUND_COLOR = '#3A3A3A'
export const TEXT_COLOR = '#A9B7C6'
export const ACTIVE_COLOR = '#CC7832'